Resturant/Canteen/urls.py
from . import views
from django.urls import path

app_name = 'canteen'
urlpatterns = [
    path('',views.index,name='index'),
    path('order/<int:id>',views.Order,name='order')
]

Resturant/Customers/urls.py
from django.urls import path
from . import views


app_name='customer'

urlpatterns = [
    path('',views.login1,name='login1'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout1,name='logout'),
]

Resturant/Resturant/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Canteen.urls')),
    path('customers/',include('Customers.urls'))
]

Resturant/Canteen/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User

class MenuOrder(models.Model):
    o_id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    item_price = models.IntegerField()
    id = models.ForeignKey(User, models.DO_NOTHING, db_column='id', blank=True, null=True)
    ordertime = models.TimeField(db_column='OrderTime', blank=True, null=True)  # Field name made lowercase.
    orderdate = models.DateField(db_column='OrderDate', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'menu_order'

Resturant/Customers/models.py
from django.db import models

# Create your models here.

Resturant/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class MenuOrder(models.Model):
    o_id = models.IntegerField(primary_key=True)
    item_name = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    item_price = models.IntegerField()
    id = models.ForeignKey('AuthUser', models.DO_NOTHING, db_column='id', blank=True, null=True)
    ordertime = models.TimeField(db_column='OrderTime', blank=True, null=True)  # Field name made lowercase.
    orderdate = models.DateField(db_column='OrderDate', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'menu_order'

Resturant/Canteen/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import MenuOrder
import datetime 
# Create your views here.

def index(request):
    return render(request,'Canteen/index (1).html')

def Order(request,id):
    if request.method == "POST":
        data = request.POST.get('button1').split("+")
        MenuOrder.objects.create(
            item_name=data[1],
            item_price= data[0],
            id= request.user,
            ordertime=datetime.datetime.now().time(),
            orderdate=datetime.datetime.now().date()
        )
        return HttpResponse(data)
    return HttpResponse('Working')

Resturant/Customers/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import authenticate ,login,logout
from django.urls import reverse
from .form import UserCreationForm
from django.contrib import messages
from django.contrib.auth import get_user_model
# Create your views here.


    
def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('canteen:index'))
    else:
        if request.method == 'POST':
            form = UserCreationForm(request=request, data=request.POST)
            if form.is_valid():
                # form.save()
                form.save()
                username = form.cleaned_data['username']
                password1 = form.cleaned_data['password1']
                user = authenticate(request,username=username, password=password1)
                login(request,user)
                return HttpResponseRedirect(reverse('canteen:index'))
        else:
            form = UserCreationForm(request=request)
        context={
            'form': form,
            'pg_name':'reg'
            }
        return render(request, 'Customers/regform.html', context)

def login1(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('canteen:index'))
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        print(username)
        print(password)
        if user is not None:
            login(request, user)
            
            return HttpResponseRedirect(reverse('canteen:index'))
        else:
            messages.error(request, "Username and Password doesn't exist")
            return render(request,'Customers/regform.html')        
    return render(request,'Customers/regform.html')

def logout1(request):
    logout(request)
    return HttpResponseRedirect(reverse('canteen:index'))

Resturant/Canteen/templates/Canteen/index (1).html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  <title>Resturant</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

<body>
  <nav>
    <nav class="navbar navbar-expand-lg ">
      <div class="container">
        <a class="navbar-brand" href="#">KU-Cafeteria</a>
        <button class="navbar-toggler" type="submit" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li id="navs" class="nav-item">
              <a class="nav-link  aria-current=" href="#">Home</a>
            </li>
            <li id="navs" class="nav-item">
              <a class="nav-link" href="#">Menu</a>
            </li>

            {% if user.is_authenticated %}
            <li id="navs" class="nav-item">
              <a class="nav-link" href="{% url 'customer:logout' %}">LogOut</a>
            </li>
            {% else %}
            <li id="navs" class="nav-item">
              <a class="nav-link" href="{% url 'customer:register' %}">Register</a>
            </li>
            <li id="navs" class="nav-item">
              <a class="nav-link" href="{% url 'customer:login1' %}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a id="active" class="nav-link active"" href=" #">Order Us</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </nav>
  <car>
    <div id="carouselExampleIndicators" class="carousel slide" data-mdb-ride="carousel" data-mdb-interval="false">
      <div class="carousel-indicators">
        <button type="submit" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
          aria-current="true" aria-label="Slide 1"></button>
        <button type="submit" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
          aria-label="Slide 2"></button>
        <button type="submit" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
          aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static '/images/c2.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static '/images/c1.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static '/images/c3.jpg' %}" class="d-block w-100" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="submit" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="submit" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

  </car>
  <div class="menu">
    <h2 class="hr-lines"> M E N U </h2>
    <div class="items col-md-10 mx-auto mt-4">
      <div class="card">
        <img src="{% static '/images/bir.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Biryani</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="200 + Chicken Biryani">200</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img id="pu" src="{% static '/images/pu2.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Pulao</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="180 + Chicken Pulao">180 </button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/cq2.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Qorma</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="200 + Chicken Qorma">200</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/ck2.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Karahi</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="200 + Chicken Karahi">200</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/ch.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Handi</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="230 + Chicken Handi">230</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="items col-md-10 mx-auto mt-4">
      <div class="card">
        <img src="{% static '/images/cf.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Fried rice</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="230 + Chicken Fried Rice">230</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/cm.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Manchurian</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="250 + Chicken Manchurian">250</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/chm.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Chowmein</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="200 + Chicken Chowmein">200</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/ccd.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Chilli Dry</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="250 + Chicken Chilli Dry">250</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/cd.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Dumplings</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="150 + Chicken Dumplings">150</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="items col-md-10 mx-auto mt-4">
      <div class="card">
        <img src="{% static '/images/cb4.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Burger</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="300 + Chicken Burger">300</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/cb2.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Broast</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="360 + Chicken Broast">360</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/bb.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Beef Burger</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="400 + Beef Burger">400</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/cr.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken roll</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="130 + dishname">130</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <img src="{% static '/images/ct.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Chicken Tikka</h5>
          {% if request.user.is_authenticated %}
          <form action="{% url 'canteen:order' request.user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="button1" value="190 + dishname">190</button>
          </form>
          {% else %}
            <center><p>Login to View price</p></center>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</body>

</html>

Resturant/Canteen/templates/Canteen/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  <title>Resturant</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

<body>
  <nav>
    <nav class="navbar navbar-expand-lg ">
      <div class="container">
        <a class="navbar-brand" href="#">KU-Cafeteria</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li id="navs" class="nav-item">
              <a class="nav-link  aria-current="  href="#">Home</a>
            </li>
            <li id="navs" class="nav-item">
              <a class="nav-link" href="#">Menu</a>
            </li>
            
            {% if user.is_authenticated %}
            <li id="navs" class="nav-item">
              <a class="nav-link" href="{% url 'customer:logout' %}">LogOut</a>
            </li>
            {% else %}
            <li id="navs" class="nav-item">
              <a class="nav-link" href="{% url 'customer:register' %}">Register</a>
            </li>
            <li id="navs" class="nav-item">
              <a class="nav-link" href="{% url 'customer:login1' %}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a id="active" class="nav-link active"" href=" #">Order Us</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </nav>
  <car>
    <div id="carouselExampleIndicators" class="carousel slide" data-mdb-ride="carousel" data-mdb-interval="false">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
          aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
          aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
          aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img  src="{% static '/images/c2.jpg' %}"class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img   src="{% static '/images/c1.jpg' %}"class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img  src="{% static '/images/c3.jpg' %}" class="d-block w-100" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

  </car>
  <div class="menu">
    <!-- <hr><h1 class="text-center mt-3">MENU</h1> -->
    <h2 class="hr-lines"> M E N U </h2>
        <div class="items col-md-10 mx-auto mt-4">
          <div class="card">
            <img src="{% static '/images/bir.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Biryani</h5>
              <form action="{% url 'canteen:order' request.user.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" name="button1" value="200 + dishName" >200</button>
              </form>
            </div>
          </div>
          <div class="card">
            <img id="pu" src="{% static '/images/pu2.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Pulao</h5>
              <button type="button" class="btn btn-primary">180</button>
            </div>
          </div>
          <div class="card">
            <img src="{% static '/images/cq2.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Qorma</h5>
              <button type="button" class="btn btn-primary">200</button>
            </div>
          </div>
          <div class="card">
            <img  src="{% static '/images/ck2.jpg' %}"class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Karahi</h5>
              <button type="button" class="btn btn-primary">200</button>
            </div>
          </div>
          <div class="card">
            <img  src="{% static '/images/ch.jpg' %}"class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Handi</h5>
              <button type="button" class="btn btn-primary">230</button>
            </div>
          </div>
        </div>
        <div class="items col-md-10 mx-auto mt-4">
          <div class="card">
            <img  src="{% static '/images/cf.jpg' %}"class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Fried rice</h5>
              <button type="button" class="btn btn-primary">230</button>
            </div>
          </div>
          <div class="card">
            <img  src="{% static '/images/cm.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Manchurian</h5>
              <button type="button" class="btn btn-primary">250</button>
            </div>
          </div>
          <div class="card">
            <img  src="{% static '/images/chm.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Chowmein</h5>
              <button type="button" class="btn btn-primary">200</button>
            </div>
          </div>
          <div class="card">
            <img  src="{% static '/images/ccd.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Chilli Dry</h5>
              <button type="button" class="btn btn-primary">250</button>
            </div>
          </div>
          <div class="card">
            <img  src="{% static '/images/cd.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Dumplings</h5>
              <button type="button" class="btn btn-primary">150</button>
            </div>
          </div>
        </div>
        <div class="items col-md-10 mx-auto mt-4">
          <div class="card">
            <img  src="{% static '/images/cb4.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Burger</h5>
              <button type="button" class="btn btn-primary">300</button>
            </div>
          </div>
          <div class="card">
            <img  src="{% static '/images/cb2.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Broast</h5>
              <button type="button" class="btn btn-primary">360</button>
            </div>
          </div>
          <div class="card">
            <img  src="{% static '/images/bb.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Beef Burger</h5>
              <button type="button" class="btn btn-primary">400</button>
            </div>
          </div>
          <div class="card">
            <img  src="{% static '/images/cr.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken roll</h5>
              <button type="button" class="btn btn-primary">130</button>
            </div>
          </div>
          <div class="card">
            <img src="{% static '/images/ct.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Chicken Tikka</h5>
              <button type="button" class="btn btn-primary">190</button>
            </div>
          </div>
        </div>
  </div>
</body>

</html>